name: Build and Push full Gitpod Workspace Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        docker_channel: stable
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: thepinsteam
        ## No one will knows about its access key.
        password: ${{ secrets.DOCKER_REGISTRY_ACCESS_KEY }}
        repository: madebythepinshub/custom-gp-workspace
        tags_with_ref: true
        dockerfile: custom-images/gp-workspace-full/Dockerfile
        push: true
        tags: latest
